name: Node.js CI

on:
  workflow_dispatch:
    inputs:
      strategyName:
        description: 'Strategy name'
        required: true
      chain:
        description: 'Chain'
        required: true
        default: 'POLYGON'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: yarn install

      - name: Run test
        working-directory: './pkg/strategies/polygon'
        run: npx hardhat test
        env:
          ETH_NODE_URI_POLYGON: ${{ secrets.ETH_NODE_URI_POLYGON }}
          ETH_NODE_URI_FANTOM: ${{ secrets.ETH_NODE_URI_FANTOM }}
          ETH_NETWORK: ${{ github.event.inputs.chain}}
          TEST_REPORT: true

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Test Report   # Name of the check run which will be created
          path: report.json    # Path to test results
          reporter: mocha-json

